language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r example/requirements.txt
script: python setup.py test
deploy:
  - provider: pypi
    user: yylucifer
    password: ${PYPI_PASSWORD}
    on:
      python: 2.7
      tags: true
      branch: master
  - provider: pypi
    user: yylucifer
    password: ${PYPI_PASSWORD}
    on:
      python: 3.6
      tags: true
      branch: master